/**
 * q2-tasks.cjs
 * Q2 SEO task template for May 2026.
 * Used by: Roman Electric, Milwaukee Signs, P2EzPay.
 * 44 parent tasks. Each has goal/description and a steps[] that becomes
 * child subtasks in the seeder.
 */
module.exports = [
  // ═══ Authority / Backlink Growth (9) ═══
  {
    title: 'Authority campaigns — target high-DR referring domains',
    taskType: 'link-building', priority: 'HIGH',
    milestone: 'Authority / Backlink Growth', assigneeKey: 'mudassar',
    goal: 'Build topical authority. Earn high-DR referring domains in the niche.',
    description: 'Run outreach campaigns targeting authoritative referring domains relevant to the niche.',
    steps: [
      'Build prospect list of authoritative sites in niche',
      'Prepare pitch templates and value-add angles',
      'Execute outreach and follow-ups',
      'Secure placements and verify live links',
    ],
  },
  {
    title: 'Competitor gap coverage — close backlink gaps vs top competitors',
    taskType: 'link-building', priority: 'HIGH',
    milestone: 'Authority / Backlink Growth', assigneeKey: 'mudassar',
    goal: 'Close backlink gaps vs top competitors to lift relative authority.',
    description: 'Identify backlinks pointing to competitors but missing for us and execute outreach to close those gaps.',
    steps: [
      'Run backlink gap analysis across top-3 competitors',
      'Filter and shortlist quality referring domains',
      'Prioritize by DR, relevance, traffic',
      'Run outreach to close the gap',
    ],
  },
  {
    title: 'Reverse engineering of competitor top-5 backlinks',
    taskType: 'link-building', priority: 'MEDIUM',
    milestone: 'Authority / Backlink Growth', assigneeKey: 'mudassar',
    goal: 'Replicate the top-performing backlinks of main competitors.',
    description: 'Break down the top-5 highest-value backlinks per competitor and plan replication tactics.',
    steps: [
      'Export each competitor top-5 backlinks',
      'Classify by link type (guest post, resource, PR, directory)',
      'Create tactic sheet per link type',
      'Schedule outreach per tactic',
    ],
  },
  {
    title: 'Acquire paid backlinks — execute outreach & placement',
    taskType: 'link-building', priority: 'HIGH',
    milestone: 'Authority / Backlink Growth', assigneeKey: 'mudassar',
    goal: 'Acquire high-quality paid backlinks on vetted domains.',
    description: 'Place paid backlinks on pre-vetted authority sites aligned with target pages.',
    steps: [
      'Validate vendor/site quality metrics',
      'Negotiate placement and anchor text',
      'Order and monitor publication',
      'Verify live link and index status',
    ],
  },
  {
    title: 'Digital PR outreach for brand authority',
    taskType: 'link-building', priority: 'HIGH',
    milestone: 'Authority / Backlink Growth', assigneeKey: 'hamza',
    goal: 'Earn brand mentions and links from PR-grade publishers.',
    description: 'Pitch story angles, data, or commentary to tier-1/2 publishers.',
    steps: [
      'Develop 2-3 pitch-ready angles',
      'Build journalist/publisher media list',
      'Send targeted pitches and follow up',
      'Track mentions, links, and brand lift',
    ],
  },
  {
    title: "Competitor's free & generic backlink building",
    taskType: 'link-building', priority: 'MEDIUM',
    milestone: 'Authority / Backlink Growth', assigneeKey: 'hamza',
    goal: 'Match competitors on free/generic backlink sources quickly.',
    description: 'Claim free backlink opportunities (directories, profiles, Q&A) competitors already have.',
    steps: [
      'Extract competitors free backlinks',
      'Identify reusable platforms (directories, forums, profiles)',
      'Submit and claim profiles with consistent NAP',
      'Log and track indexation',
    ],
  },
  {
    title: 'Monitor competitor new backlinks (weekly)',
    taskType: 'link-building', priority: 'MEDIUM',
    milestone: 'Authority / Backlink Growth', assigneeKey: 'hamza',
    goal: 'React quickly to competitor link-building moves.',
    description: 'Track new backlinks competitors acquire each week and evaluate replication.',
    steps: [
      'Set weekly Ahrefs/Semrush alerts for competitors',
      'Export new referring domains weekly',
      'Score each for replication potential',
      'Add viable targets to outreach pipeline',
    ],
  },
  {
    title: 'Competitor keyword adjustment in existing content',
    taskType: 'on-page-seo', priority: 'MEDIUM',
    milestone: 'Authority / Backlink Growth', assigneeKey: 'mudassar',
    goal: 'Recover rankings where competitors moved ahead via content shifts.',
    description: 'Re-optimize existing pages with the keywords and angles top competitors now rank for.',
    steps: [
      'Identify pages losing ranking to competitors',
      'Extract keywords competitors added or strengthened',
      'Rewrite/expand our pages to match and exceed',
      'Re-submit in GSC and monitor movement',
    ],
  },
  {
    title: 'Find new content strategy opportunities',
    taskType: 'content-writing', priority: 'MEDIUM',
    milestone: 'Authority / Backlink Growth', assigneeKey: 'mudassar',
    goal: 'Unlock new rankable content directions for the quarter.',
    description: 'Research fresh content opportunities rooted in search demand and business relevance.',
    steps: [
      'Review SERP trends and forum/Reddit/AI-assistant queries',
      'Map gaps not yet covered on our site',
      'Propose 3-5 new content pillars or series',
      'Prioritize by ROI and effort',
    ],
  },

  // ═══ Backlink Opportunity Research (5) ═══
  {
    title: 'Find free & paid opportunity for low-hang keywords',
    taskType: 'link-building', priority: 'MEDIUM',
    milestone: 'Backlink Opportunity Research', assigneeKey: 'mudassar',
    goal: 'Surface the easiest wins for backlink targeting on low-hang KWs.',
    description: 'Compile free + paid backlink opportunities specifically aligned with low-competition keyword pages.',
    steps: [
      'Pull low-hang keyword pages from rank tracker',
      'Match each to supporting backlink opportunities',
      'Split opportunities into free vs paid',
      'Hand off prioritized list to outreach',
    ],
  },
  {
    title: "Finalise paid backlink's website list",
    taskType: 'link-building', priority: 'MEDIUM',
    milestone: 'Backlink Opportunity Research', assigneeKey: 'mudassar',
    goal: 'Lock in vetted domains for paid placement this quarter.',
    description: 'Review, score, and finalise the paid-backlink site list with clear quality gates.',
    steps: [
      'Score sites by DR, organic traffic, topical fit',
      'Filter out toxic/thin-content sites',
      'Confirm pricing and turnaround per site',
      'Publish final vendor list with notes',
    ],
  },
  {
    title: 'Identify keyword / page for paid backlink targeting',
    taskType: 'link-building', priority: 'MEDIUM',
    milestone: 'Backlink Opportunity Research', assigneeKey: 'mudassar',
    goal: 'Point paid link equity at the highest-ROI pages.',
    description: 'Map each paid backlink to a specific target page and keyword to maximise ranking uplift.',
    steps: [
      'List pages currently at positions 5-20',
      'Choose target keyword per page',
      'Plan anchor text diversity',
      'Assign paid links to target pages',
    ],
  },
  {
    title: 'Authority campaigns for 20 low-hang KW pages',
    taskType: 'link-building', priority: 'HIGH',
    milestone: 'Backlink Opportunity Research', assigneeKey: 'hamza',
    goal: 'Push 20 close-to-win pages into top-3 with focused link campaigns.',
    description: 'Run a concentrated authority campaign across 20 low-hang keyword pages.',
    steps: [
      'Select 20 target pages and keywords',
      'Build link plan per page (mix of tactics)',
      'Execute outreach and secure placements',
      'Track ranking shifts weekly',
    ],
  },
  {
    title: 'Acquire backlinks from paid resources',
    taskType: 'link-building', priority: 'HIGH',
    milestone: 'Backlink Opportunity Research', assigneeKey: 'hamza',
    goal: 'Execute paid placements quickly with quality control.',
    description: 'Place paid backlinks from the approved vendor list against the target pages.',
    steps: [
      'Brief each vendor with target URL and anchor',
      'Approve draft content before publish',
      'Verify live URLs and indexation',
      'Log placements in backlink tracker',
    ],
  },

  // ═══ Local SEO Expansion (4) ═══
  {
    title: 'GBP growth & optimization',
    taskType: 'local-seo', priority: 'HIGH',
    milestone: 'Local SEO Expansion', assigneeKey: 'hamza',
    goal: 'Grow GBP visibility, calls, and direction requests.',
    description: 'Optimize the Google Business Profile to maximise local pack presence and engagement.',
    steps: [
      'Audit and complete all GBP fields',
      'Add services, products, attributes',
      'Publish weekly posts and offers',
      'Monitor insights and iterate',
    ],
  },
  {
    title: 'Reviews acquisition strategy',
    taskType: 'local-seo', priority: 'MEDIUM',
    milestone: 'Local SEO Expansion', assigneeKey: 'hamza',
    goal: 'Grow verified review volume, velocity, and rating.',
    description: 'Set up a repeatable process to earn genuine customer reviews.',
    steps: [
      'Generate review request links',
      'Build email/SMS follow-up cadence',
      'Train staff on in-person asks',
      'Monitor and respond to all reviews',
    ],
  },
  {
    title: 'Local schema implementation',
    taskType: 'local-seo', priority: 'MEDIUM',
    milestone: 'Local SEO Expansion', assigneeKey: 'hamza',
    goal: 'Help search engines understand location and services.',
    description: 'Implement LocalBusiness / Service schema on key location and landing pages.',
    steps: [
      'Pick schema types (LocalBusiness, Service, FAQ)',
      'Draft JSON-LD blocks per page',
      'Deploy and validate with Rich Results Test',
      'Monitor schema errors in GSC',
    ],
  },
  {
    title: 'Add local testimonials to key landing pages',
    taskType: 'local-seo', priority: 'LOW',
    milestone: 'Local SEO Expansion', assigneeKey: 'hamza',
    goal: 'Increase trust and local relevance on top converting pages.',
    description: 'Surface local customer testimonials on priority landing pages.',
    steps: [
      'Collect verified local testimonials',
      'Add Review schema where eligible',
      'Place testimonials above the fold',
      'Test conversion impact',
    ],
  },

  // ═══ AEO / GEO Content Optimization (7) ═══
  {
    title: 'Create and ready content for low-hang KW',
    taskType: 'content-writing', priority: 'HIGH',
    milestone: 'AEO / GEO Content Optimization', assigneeKey: 'bisma',
    goal: 'Ship AEO-ready content for the low-hang KW list.',
    description: 'Produce new/updated content targeting the low-hang keyword set with AEO formatting.',
    steps: [
      'Assign keywords to pages/briefs',
      'Write content with direct answers + supporting depth',
      'Add FAQs and structured formatting',
      'Publish and index via GSC',
    ],
  },
  {
    title: 'Implement schema on optimized pages',
    taskType: 'schema-deployment', priority: 'HIGH',
    milestone: 'AEO / GEO Content Optimization', assigneeKey: 'bisma',
    goal: 'Increase rich result eligibility and AI-engine pickup.',
    description: 'Deploy appropriate schema (FAQ/HowTo/Article/Product) on optimized pages.',
    steps: [
      'Pick schema type per page',
      'Write and deploy JSON-LD',
      'Validate in Rich Results Test',
      'Monitor enhancements in GSC',
    ],
  },
  {
    title: 'Entity strengthening across site',
    taskType: 'aeo-geo', priority: 'MEDIUM',
    milestone: 'AEO / GEO Content Optimization', assigneeKey: 'bisma',
    goal: 'Establish clearer entity relationships for AI search.',
    description: 'Reinforce the sites entity graph via consistent naming, internal linking, and external references.',
    steps: [
      'Define core entities (brand, people, services, places)',
      'Align on-page mentions and metadata',
      'Add sameAs references and structured data',
      'Strengthen internal linking around entities',
    ],
  },
  {
    title: 'Analyse & improve FAQ section',
    taskType: 'aeo-geo', priority: 'MEDIUM',
    milestone: 'AEO / GEO Content Optimization', assigneeKey: 'bisma',
    goal: 'Improve AEO capture by mining real user questions.',
    description: 'Audit current FAQ coverage and add the most-asked user questions with concise answers.',
    steps: [
      'Export current FAQs per page',
      'Mine PAA, AI, and search suggest for new questions',
      'Rewrite weak answers; add missing ones',
      'Deploy FAQ schema',
    ],
  },
  {
    title: 'Structured content formatting (lists, tables, headings)',
    taskType: 'aeo-geo', priority: 'MEDIUM',
    milestone: 'AEO / GEO Content Optimization', assigneeKey: 'bisma',
    goal: 'Make content easier for engines and LLMs to extract.',
    description: 'Reformat core pages into snippet-friendly structures (lists, tables, clear headings).',
    steps: [
      'Identify pages with poor formatting',
      'Break walls of text into headings and lists',
      'Add comparison tables where relevant',
      'Keep paragraphs short and scannable',
    ],
  },
  {
    title: 'Voice search optimization',
    taskType: 'aeo-geo', priority: 'MEDIUM',
    milestone: 'AEO / GEO Content Optimization', assigneeKey: 'bisma',
    goal: 'Capture conversational / voice queries.',
    description: 'Rework pages to answer natural-language, question-form queries clearly.',
    steps: [
      'Target question-based keywords',
      'Use natural conversational phrasing',
      'Provide 40-60 word concise answers',
      'Optimize mobile speed and UX',
    ],
  },
  {
    title: 'Entity-based SEO optimization',
    taskType: 'aeo-geo', priority: 'MEDIUM',
    milestone: 'AEO / GEO Content Optimization', assigneeKey: 'bisma',
    goal: 'Expand topical semantic coverage.',
    description: 'Enhance content with related entities and semantically connected topics.',
    steps: [
      'Identify primary entities per page',
      'Add related semantic terms and sub-topics',
      'Improve contextual internal linking',
      'Track topical coverage gains',
    ],
  },

  // ═══ GSC Monitoring (4) ═══
  {
    title: 'Coverage report & indexing monitoring',
    taskType: 'reporting', priority: 'HIGH',
    milestone: 'GSC Monitoring', assigneeKey: 'sami',
    goal: 'Keep priority pages indexed and healthy.',
    description: 'Monitor Coverage/Indexing reports weekly and resolve excluded/errored URLs.',
    steps: [
      'Review Coverage report weekly',
      'Identify excluded/errored URLs',
      'Fix root causes (robots, canonical, duplicates)',
      'Request re-indexing where needed',
    ],
  },
  {
    title: 'Crawl error fixes from GSC',
    taskType: 'crawl-fix', priority: 'HIGH',
    milestone: 'GSC Monitoring', assigneeKey: 'sami',
    goal: 'Reduce crawl waste and fix broken paths.',
    description: 'Close out crawl errors reported in GSC.',
    steps: [
      'Export GSC crawl errors',
      'Classify by error type',
      'Implement fixes (redirects, status codes)',
      'Validate fixes in GSC',
    ],
  },
  {
    title: 'Content insights & performance analysis',
    taskType: 'reporting', priority: 'MEDIUM',
    milestone: 'GSC Monitoring', assigneeKey: 'sami',
    goal: 'Turn GSC signals into optimisation decisions.',
    description: 'Analyse impressions, clicks, CTR and rankings to drive the content plan.',
    steps: [
      'Pull GSC performance data',
      'Identify rising and falling queries/pages',
      'Flag pages for optimisation',
      'Share insights with content team',
    ],
  },
  {
    title: 'Sitemap submission monitoring',
    taskType: 'reporting', priority: 'MEDIUM',
    milestone: 'GSC Monitoring', assigneeKey: 'sami',
    goal: 'Keep sitemaps accurate and discoverable.',
    description: 'Verify XML sitemap health and discovery.',
    steps: [
      'Check sitemap status in GSC',
      'Remove invalid/noindex URLs',
      'Add new pages promptly',
      'Resubmit and track indexed counts',
    ],
  },

  // ═══ Content Scaling (4) ═══
  {
    title: 'Blog expansion — publish monthly batch',
    taskType: 'content-writing', priority: 'MEDIUM',
    milestone: 'Content Scaling', assigneeKey: 'bisma',
    goal: 'Keep a steady content cadence live.',
    description: 'Publish the monthly blog batch per editorial calendar.',
    steps: [
      'Finalise monthly topic list',
      'Brief, write, edit each post',
      'Publish with SEO metadata and schema',
      'Submit to GSC for indexing',
    ],
  },
  {
    title: 'Supporting content creation for pillars',
    taskType: 'content-writing', priority: 'MEDIUM',
    milestone: 'Content Scaling', assigneeKey: 'bisma',
    goal: 'Strengthen pillars with cluster support.',
    description: 'Produce supporting articles that link to and reinforce pillar pages.',
    steps: [
      'List pillars needing support',
      'Identify cluster topics per pillar',
      'Write and interlink supporting pieces',
      'Measure pillar movement',
    ],
  },
  {
    title: 'Content gap filling (missing intent coverage)',
    taskType: 'content-writing', priority: 'MEDIUM',
    milestone: 'Content Scaling', assigneeKey: 'bisma',
    goal: 'Cover the intents we are missing vs competitors.',
    description: 'Produce new pages/sections that close intent gaps.',
    steps: [
      'Run SERP intent gap analysis',
      'Prioritize by business value',
      'Brief and produce content',
      'Publish and internal-link',
    ],
  },
  {
    title: 'Track referral traffic from published content',
    taskType: 'reporting', priority: 'MEDIUM',
    milestone: 'Content Scaling', assigneeKey: 'sami',
    goal: 'Measure downstream value of content.',
    description: 'Monitor referral traffic and conversions sent by newly published content.',
    steps: [
      'Tag content with UTM where relevant',
      'Track referral sources in GA',
      'Attribute conversions per asset',
      'Share top performers with team',
    ],
  },

  // ═══ Topical Authority Building (4) ═══
  {
    title: 'Audit topical coverage & pillar pages',
    taskType: 'content-audit', priority: 'MEDIUM',
    milestone: 'Topical Authority Building', assigneeKey: 'bisma',
    goal: 'Baseline topical coverage and pillar health.',
    description: 'Assess how well current content covers core topics and pillars.',
    steps: [
      'Map existing content to pillars',
      'Score depth and freshness per pillar',
      'Highlight weak/thin pillars',
      'Produce action plan per pillar',
    ],
  },
  {
    title: 'Expand cluster pages around pillars',
    taskType: 'content-writing', priority: 'MEDIUM',
    milestone: 'Topical Authority Building', assigneeKey: 'bisma',
    goal: 'Add breadth to each pillar cluster.',
    description: 'Create new cluster pages that expand topical breadth.',
    steps: [
      'Pick clusters needing expansion',
      'Brief new cluster pages',
      'Publish and interlink within cluster',
      'Track pillar ranking impact',
    ],
  },
  {
    title: 'Interlink clusters with pillars',
    taskType: 'link-building', priority: 'MEDIUM',
    milestone: 'Topical Authority Building', assigneeKey: 'bisma',
    goal: 'Route authority inside each cluster correctly.',
    description: 'Strengthen internal linking between cluster pages and their pillars.',
    steps: [
      'Map current internal links per cluster',
      'Add missing cluster→pillar links',
      'Add contextual cross-cluster links',
      'Re-crawl and verify link equity flow',
    ],
  },
  {
    title: 'Schema expansion across new clusters',
    taskType: 'schema-deployment', priority: 'MEDIUM',
    milestone: 'Topical Authority Building', assigneeKey: 'mudassar',
    goal: 'Bring new clusters to rich-result parity.',
    description: 'Deploy schema on newly expanded cluster content.',
    steps: [
      'Pick schema types per cluster page',
      'Deploy JSON-LD',
      'Validate with Rich Results Test',
      'Monitor enhancements in GSC',
    ],
  },

  // ═══ Backlink Growth (3) ═══
  {
    title: 'Update old content — refresh & re-optimize',
    taskType: 'content-writing', priority: 'MEDIUM',
    milestone: 'Backlink Growth', assigneeKey: 'bisma',
    goal: 'Recover decayed rankings via refresh.',
    description: 'Update dated content to recover rankings and attract new links.',
    steps: [
      'Identify pages with declining traffic',
      'Refresh facts, examples, year references',
      'Improve depth and structure',
      'Re-submit in GSC',
    ],
  },
  {
    title: 'Disavow toxic backlinks',
    taskType: 'link-building', priority: 'HIGH',
    milestone: 'Backlink Growth', assigneeKey: 'hamza',
    goal: 'Protect the site from harmful backlink signals.',
    description: 'Audit and disavow toxic backlinks as needed.',
    steps: [
      'Pull full backlink profile',
      'Flag toxic/spammy domains',
      'Attempt removal outreach where practical',
      'Submit disavow file to Google',
    ],
  },
  {
    title: 'Update FAQs from FAQ cluster analysis',
    taskType: 'aeo-geo', priority: 'MEDIUM',
    milestone: 'Backlink Growth', assigneeKey: 'bisma',
    goal: 'Keep FAQ clusters aligned with current user intent.',
    description: 'Refresh FAQs across the site based on cluster analysis.',
    steps: [
      'Export current FAQ inventory',
      'Cluster by topic / intent',
      'Rewrite, add, or remove FAQs',
      'Re-deploy FAQ schema',
    ],
  },

  // ═══ Advanced Technical SEO (4) ═══
  {
    title: 'Perform technical SEO audit',
    taskType: 'technical-seo', priority: 'HIGH',
    milestone: 'Advanced Technical SEO', assigneeKey: 'hamza',
    goal: 'Surface and prioritize technical SEO debt.',
    description: 'Run a full technical SEO audit across crawl, index, render, and performance signals.',
    steps: [
      'Run Screaming Frog / Sitebulb crawl',
      'Review GSC + CWV + indexation reports',
      'Document issues with severity',
      'Publish prioritized fix plan',
    ],
  },
  {
    title: 'Crawl budget optimization',
    taskType: 'technical-seo', priority: 'MEDIUM',
    milestone: 'Advanced Technical SEO', assigneeKey: 'hamza',
    goal: 'Ensure Google spends crawl budget on valuable pages.',
    description: 'Identify and fix crawl-budget waste.',
    steps: [
      'Analyse log files / crawl stats',
      'Identify wasted crawl (params, duplicates, noindex)',
      'Tighten robots, internal links, sitemaps',
      'Re-measure crawl efficiency',
    ],
  },
  {
    title: 'Core Web Vitals improvements',
    taskType: 'technical-seo', priority: 'HIGH',
    milestone: 'Advanced Technical SEO', assigneeKey: 'awais',
    goal: 'Move CWV into Good across key templates.',
    description: 'Drive LCP/INP/CLS improvements on priority templates.',
    steps: [
      'Identify templates failing CWV',
      'Fix render-blocking resources and LCP images',
      'Address layout shift and interaction latency',
      'Re-measure in CrUX/Lighthouse',
    ],
  },
  {
    title: 'Schema markup validation (structured data testing)',
    taskType: 'schema-deployment', priority: 'MEDIUM',
    milestone: 'Advanced Technical SEO', assigneeKey: 'mudassar',
    goal: 'Keep schema error-free and enhancements-eligible.',
    description: 'Validate existing schema across templates and fix issues.',
    steps: [
      'Crawl for schema across templates',
      'Validate with Rich Results Test',
      'Fix errors and warnings',
      'Monitor Enhancements in GSC',
    ],
  },

  // ═══ Q1 Carryover (1) ═══
  {
    title: 'Complete pending Q1 activities (carryover)',
    taskType: 'content-audit', priority: 'LOW',
    milestone: 'Q1 Carryover', assigneeKey: 'bisma',
    goal: 'Close the loop on any unfinished Q1 items.',
    description: 'Track down and complete items that slipped from Q1.',
    steps: [
      'List unfinished Q1 tasks per project',
      'Re-scope and re-assign where needed',
      'Complete or explicitly deprioritize',
      'Update reporting with final status',
    ],
  },
];
