/**
 * wilhelmina-tasks.cjs
 * Wilhelmina Balloon: Q1 Ongoing SEO (Pages 1-20) + SEO Foundation Setup.
 * 66 parent tasks (41 Ongoing SEO + 25 Foundation Setup).
 */
module.exports = [
  // ═══ A. Ongoing SEO Activities (Pages 1-20) ═══

  // Keyword Research (3)
  {
    title: 'Search intent analysis (Pages 1-20)',
    taskType: 'keyword-research', priority: 'HIGH',
    milestone: 'A. Ongoing SEO — Keyword Research', assigneeKey: 'mudassar',
    goal: 'Match content with user intent. Improve rankings and engagement. Increase conversions.',
    description: 'Analyze what users want when searching for your target keywords and align content accordingly.',
    steps: [
      'Identify target keywords for each page',
      'Classify intent (informational, navigational, transactional, commercial)',
      'Study top-ranking SERP content per keyword',
      'Adjust pages to match the dominant intent',
    ],
  },
  {
    title: 'Keyword research (Pages 1-20)',
    taskType: 'keyword-research', priority: 'HIGH',
    milestone: 'A. Ongoing SEO — Keyword Research', assigneeKey: 'mudassar',
    goal: 'Identify the right keywords driving qualified traffic and conversions.',
    description: 'Build a prioritized keyword list per page using volume, difficulty, intent, and business value.',
    steps: [
      'Seed from business services and existing rankings',
      'Expand via Ahrefs/Semrush + Search Console',
      'Filter by volume, KD and intent alignment',
      'Assign primary + secondary keywords per page',
    ],
  },
  {
    title: 'Incorporating primary & secondary keywords (Pages 1-20)',
    taskType: 'keyword-research', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — Keyword Research', assigneeKey: 'mudassar',
    goal: 'Ensure each page targets a clear primary KW with supporting secondaries.',
    description: 'Map primary + secondary keywords onto each page and weave them into copy naturally.',
    steps: [
      'Update KW-to-page mapping sheet',
      'Assign 1 primary + 3-5 secondaries',
      'Weave naturally into titles, headings and body',
      'Flag and resolve cannibalization',
    ],
  },

  // Keyword Integration (2)
  {
    title: 'Meta tags title & description optimization (Pages 1-20)',
    taskType: 'on-page-seo', priority: 'HIGH',
    milestone: 'A. Ongoing SEO — Keyword Integration', assigneeKey: 'bisma',
    goal: 'Improve CTR and relevance signals on priority pages.',
    description: 'Rewrite titles and meta descriptions with the primary keyword, value prop, and CTA within limits.',
    steps: [
      'Audit current title + meta length and KW usage',
      'Rewrite each title (≤60 chars) and meta (≤155 chars)',
      'Include primary KW near start of title',
      'Deploy and monitor CTR in GSC',
    ],
  },
  {
    title: 'Header tags H1-H6 optimization (Pages 1-20)',
    taskType: 'on-page-seo', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — Keyword Integration', assigneeKey: 'bisma',
    goal: 'Improve content structure, scannability, and semantic signals.',
    description: 'Ensure a single H1, logical H2/H3 hierarchy, and keyword-relevant subheadings.',
    steps: [
      'Audit heading outline per page',
      'Enforce single H1 with primary KW',
      'Rewrite H2/H3s with secondary KWs and user questions',
      'Validate hierarchy with a heading outline tool',
    ],
  },

  // Content Audit & Refresh (4)
  {
    title: 'Existing content quality check (Pages 1-20)',
    taskType: 'content-audit', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — Content Audit & Refresh', assigneeKey: 'bisma',
    goal: 'Identify weak, thin, or outdated sections that hurt rankings.',
    description: 'Score each page on depth, clarity, freshness, originality, and intent match.',
    steps: [
      'Rubric-score each page',
      'Flag thin/outdated sections',
      'Decide rewrite vs refresh vs keep',
      'Queue actions with owners',
    ],
  },
  {
    title: 'Content gap analysis (Pages 1-20)',
    taskType: 'content-audit', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — Content Audit & Refresh', assigneeKey: 'bisma',
    goal: 'Find topics/angles competitors cover that we do not.',
    description: 'Compare our page coverage vs top competitors and list missing sections/questions.',
    steps: [
      'Pull top-3 competitor outlines per target page',
      'Diff headings and PAA coverage',
      'Record missing topics per page',
      'Feed gaps into the update plan',
    ],
  },
  {
    title: 'Content update & expansion (Pages 1-20)',
    taskType: 'content-writing', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — Content Audit & Refresh', assigneeKey: 'bisma',
    goal: 'Close identified gaps and lift rankings + time-on-page.',
    description: 'Update and expand pages to match intent, fill gaps, and refresh dated examples.',
    steps: [
      'Rewrite weak sections with gap-filler content',
      'Refresh facts, examples, year references',
      'Add FAQs and supporting visuals',
      'Re-submit URLs in GSC',
    ],
  },
  {
    title: 'Duplicate content fixes (Pages 1-20)',
    taskType: 'content-audit', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — Content Audit & Refresh', assigneeKey: 'bisma',
    goal: 'Prevent dilution from duplicate or near-duplicate content.',
    description: 'Identify internal duplicates/boilerplate and consolidate, rewrite, or canonicalize.',
    steps: [
      'Run Siteliner / Screaming Frog duplicate detection',
      'Classify duplicates',
      'Rewrite or canonicalize',
      'Verify via re-crawl',
    ],
  },

  // UI/UX Audit (5)
  {
    title: 'Mobile responsiveness check (Pages 1-20)',
    taskType: 'technical-seo', priority: 'HIGH',
    milestone: 'A. Ongoing SEO — UI/UX Audit', assigneeKey: 'awais',
    goal: 'Ensure a smooth mobile experience for the mobile-first index.',
    description: 'Audit each page on mobile and fix layout, tap, viewport, and CLS issues.',
    steps: [
      'Run Lighthouse mobile on each page',
      'Fix tap targets, font sizes, viewport issues',
      'Resolve horizontal scroll and CLS',
      'Re-test and document fixes',
    ],
  },
  {
    title: 'Page layout & design improvements (Pages 1-20)',
    taskType: 'ux-audit', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — UI/UX Audit', assigneeKey: 'awais',
    goal: 'Improve clarity, scannability, and conversions.',
    description: 'Tune layout and visual hierarchy of priority pages.',
    steps: [
      'Audit above-the-fold clarity and CTA visibility',
      'Improve spacing, typography, hierarchy',
      'Add supporting visuals where helpful',
      'Validate with heatmaps',
    ],
  },
  {
    title: 'User journey analysis (Pages 1-20)',
    taskType: 'ux-audit', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — UI/UX Audit', assigneeKey: 'awais',
    goal: 'Understand where users drop off and why.',
    description: 'Map the user journey per page and identify friction points.',
    steps: [
      'Map journeys from entry to conversion',
      'Identify drop-offs via GA funnels',
      'Correlate with session recordings',
      'Propose targeted fixes',
    ],
  },
  {
    title: 'Navigation optimization (Pages 1-20)',
    taskType: 'ux-audit', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — UI/UX Audit', assigneeKey: 'awais',
    goal: 'Make primary paths obvious from any page.',
    description: 'Optimize menus, breadcrumbs, and internal links for usability and SEO.',
    steps: [
      'Audit main nav, footer, contextual links',
      'Simplify nav labels',
      'Add breadcrumbs where missing',
      'Validate crawl paths',
    ],
  },
  {
    title: 'Bounce rate improvement areas (Pages 1-20)',
    taskType: 'ux-audit', priority: 'LOW',
    milestone: 'A. Ongoing SEO — UI/UX Audit', assigneeKey: 'awais',
    goal: 'Reduce bounce on high-traffic / high-bounce pages.',
    description: 'Identify and address the main reasons users leave quickly.',
    steps: [
      'List top-10 high-bounce pages',
      'Diagnose (speed, intent, layout)',
      'Apply targeted fixes',
      'Re-measure after changes',
    ],
  },

  // URL Structure (4)
  {
    title: 'SEO-friendly URL creation (Pages 1-20)',
    taskType: 'on-page-seo', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — URL Structure', assigneeKey: 'bisma',
    goal: 'Clean, keyword-rich, stable URLs.',
    description: 'Review URL slugs and plan any changes with 301s.',
    steps: [
      'Audit current slugs',
      'Propose clean, short, KW-bearing slugs',
      'Plan 301 redirects',
      'Deploy and verify',
    ],
  },
  {
    title: 'Readability optimization (Pages 1-20)',
    taskType: 'on-page-seo', priority: 'LOW',
    milestone: 'A. Ongoing SEO — URL Structure', assigneeKey: 'bisma',
    goal: 'Improve readability score and user comprehension.',
    description: 'Tighten sentences, simplify wording, and improve formatting.',
    steps: [
      'Check readability (Hemingway / Flesch)',
      'Shorten sentences and paragraphs',
      'Break walls of text with headings/lists',
      'Re-measure readability score',
    ],
  },
  {
    title: 'Keyword inclusion in URLs (Pages 1-20)',
    taskType: 'on-page-seo', priority: 'LOW',
    milestone: 'A. Ongoing SEO — URL Structure', assigneeKey: 'bisma',
    goal: 'Keep URL signals aligned with target keywords.',
    description: 'Ensure primary keyword is present in the URL slug where safe to change.',
    steps: [
      'Verify slug contains primary KW',
      'Plan safe rewrites with redirects',
      'Deploy and monitor indexation',
      'Document changes',
    ],
  },
  {
    title: 'Canonicalization handling (Pages 1-20)',
    taskType: 'technical-seo', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — URL Structure', assigneeKey: 'hamza',
    goal: 'Prevent duplicate indexing and ranking dilution.',
    description: 'Audit and fix canonical tag coverage across priority pages.',
    steps: [
      'Crawl for missing / conflicting canonicals',
      'Set self-canonicals where appropriate',
      'Resolve parameter / pagination canonicals',
      'Verify in GSC Coverage',
    ],
  },

  // CTA Button Audit (2)
  {
    title: 'CTA placement analysis (Pages 1-20)',
    taskType: 'cro', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — CTA Button Audit', assigneeKey: 'bisma',
    goal: 'Lift conversion rate via better CTA positioning.',
    description: 'Analyse current CTA placement and visibility versus user attention paths.',
    steps: [
      'Map current CTA positions per page',
      'Cross-reference with heatmaps',
      'Define new placement hypotheses',
      'Prioritize A/B tests',
    ],
  },
  {
    title: 'CTA design & visibility improvement (Pages 1-20)',
    taskType: 'cro', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — CTA Button Audit', assigneeKey: 'bisma',
    goal: 'Make primary CTAs unmissable and compelling.',
    description: 'Improve CTA copy, contrast, size and supporting microcopy.',
    steps: [
      'Rewrite CTA copy (value-led)',
      'Strengthen contrast and size',
      'Add trust microcopy near CTAs',
      'Ship and monitor lift',
    ],
  },

  // Content Enhancement — 4 Blog Posts (5)
  {
    title: 'Topic research for 4 blog posts',
    taskType: 'content-writing', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — Content Enhancement (4 Blog Posts)', assigneeKey: 'bisma',
    goal: 'Select 4 high-intent, rankable blog topics.',
    description: 'Research and shortlist 4 blog topics with real search demand.',
    steps: [
      'Seed topics from KW research and PAA',
      'Score by volume / difficulty / value',
      'Validate intent vs SERPs',
      'Get approval on the 4 final topics',
    ],
  },
  {
    title: 'Keyword-based content creation (4 blogs)',
    taskType: 'content-writing', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — Content Enhancement (4 Blog Posts)', assigneeKey: 'bisma',
    goal: 'Write content anchored to real keyword demand.',
    description: 'Brief and draft the 4 blog posts around primary + secondary keywords.',
    steps: [
      'Create SEO briefs per topic',
      'Draft with KW placement + depth',
      'Add images, schema, internal links',
      'Peer-review before publish',
    ],
  },
  {
    title: 'Blog content writing & optimization (4 blogs)',
    taskType: 'content-writing', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — Content Enhancement (4 Blog Posts)', assigneeKey: 'bisma',
    goal: 'Finalize on-page SEO across all 4 blogs.',
    description: 'Polish titles, metas, headings, images, and internal links per post.',
    steps: [
      'Optimize titles, meta, H1s',
      'Add alt text and internal links',
      'Check readability and flow',
      'Final QA before publish',
    ],
  },
  {
    title: 'Internal linking integration for blogs',
    taskType: 'link-building', priority: 'LOW',
    milestone: 'A. Ongoing SEO — Content Enhancement (4 Blog Posts)', assigneeKey: 'bisma',
    goal: 'Route authority to and from the new blogs.',
    description: 'Add contextual links from related pages into the new blogs, and vice versa.',
    steps: [
      'Identify existing relevant pages',
      'Add contextual links into new blogs',
      'Add links out to pillars / services',
      'Re-crawl to verify',
    ],
  },
  {
    title: 'Blog publishing & indexing',
    taskType: 'content-writing', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — Content Enhancement (4 Blog Posts)', assigneeKey: 'bisma',
    goal: 'Get new blogs indexed quickly.',
    description: 'Publish, submit, and verify indexation for all 4 posts.',
    steps: [
      'Publish to CMS with correct metadata',
      'Submit URLs in GSC',
      'Verify indexation',
      'Share internally for promotion',
    ],
  },

  // Competitive Analysis (4)
  {
    title: 'Competitor keyword analysis',
    taskType: 'keyword-research', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — Competitive Analysis', assigneeKey: 'mudassar',
    goal: 'Find keywords competitors rank for that we should target.',
    description: 'Export competitor keyword sets and score for priority.',
    steps: [
      'Pull KW sets for top-3 competitors',
      'Filter by relevance and winnable difficulty',
      'Map winners to our page plan',
      'Share prioritized list with content',
    ],
  },
  {
    title: 'Competitor content review',
    taskType: 'content-audit', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — Competitive Analysis', assigneeKey: 'bisma',
    goal: 'Understand what competitor content does better than ours.',
    description: 'Deconstruct competitor top pages to extract winning patterns.',
    steps: [
      'Pick competitor top-5 pages per topic',
      'Break down outline, depth, media, schema',
      'List patterns we should adopt',
      'Apply insights to our briefs',
    ],
  },
  {
    title: 'Competitor backlink analysis',
    taskType: 'link-building', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — Competitive Analysis', assigneeKey: 'mudassar',
    goal: 'Find backlink sources we can replicate.',
    description: 'Review competitor referring domains and tag replication opportunities.',
    steps: [
      'Export referring domains per competitor',
      'Filter for quality and relevance',
      'Tag replicable vs PR-only',
      'Add replicable sources to outreach',
    ],
  },
  {
    title: 'Backlink / keyword gap identification',
    taskType: 'content-audit', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — Competitive Analysis', assigneeKey: 'mudassar',
    goal: 'Turn competitive findings into an action plan.',
    description: 'Synthesize gaps into a prioritized action plan with owners.',
    steps: [
      'Consolidate KW + link gaps',
      'Prioritize by impact/effort',
      'Assign owners and due dates',
      'Track monthly progress',
    ],
  },

  // Backlink Opportunity Research (3)
  {
    title: 'Competitor backlink gap analysis',
    taskType: 'link-building', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — Backlink Opportunity Research', assigneeKey: 'mudassar',
    goal: 'Close backlink gaps vs top competitors.',
    description: 'Identify backlinks pointing to competitors but not to us, and queue outreach.',
    steps: [
      'Run backlink gap analysis across top-3 competitors',
      'Filter for quality referring domains',
      'Prioritize by DR, relevance, traffic',
      'Hand off to outreach',
    ],
  },
  {
    title: 'High-authority site identification',
    taskType: 'link-building', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — Backlink Opportunity Research', assigneeKey: 'mudassar',
    goal: 'Build a curated list of high-DR targets.',
    description: 'Identify high-authority domains worth pursuing for backlinks.',
    steps: [
      'Mine lists via Ahrefs/Semrush',
      'Score by DR, relevance, traffic',
      'Check for editorial / outreach feasibility',
      'Publish target list',
    ],
  },
  {
    title: 'Outreach target list creation',
    taskType: 'link-building', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — Backlink Opportunity Research', assigneeKey: 'hamza',
    goal: 'Prepare a ready-to-execute outreach list.',
    description: 'Compile contacts, angles, and pitch variants for the target list.',
    steps: [
      'Find contact emails per target',
      'Draft pitch variants per angle',
      'Set up tracking / CRM',
      'Kick off outreach',
    ],
  },

  // AEO/GEO — 4 New Blog Pages (5)
  {
    title: 'Featured snippet optimization (4 new blogs)',
    taskType: 'aeo-geo', priority: 'HIGH',
    milestone: 'A. Ongoing SEO — AEO/GEO (4 New Blog Pages)', assigneeKey: 'bisma',
    goal: 'Capture featured snippets on the 4 new blogs.',
    description: 'Format sections to win featured snippets (paragraph/list/table).',
    steps: [
      'Identify target snippet queries per blog',
      'Structure answers to snippet format',
      'Add concise 40-60 word answers',
      'Track snippet wins in GSC',
    ],
  },
  {
    title: 'FAQ section creation (4 new blogs)',
    taskType: 'aeo-geo', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — AEO/GEO (4 New Blog Pages)', assigneeKey: 'bisma',
    goal: 'Capture PAA and AEO visibility.',
    description: 'Add high-quality FAQs with concise answers to each new blog.',
    steps: [
      'Mine PAA and AI questions',
      'Draft 40-60 word answers',
      'Add FAQ schema',
      'Monitor rich result pickup',
    ],
  },
  {
    title: 'Structured content formatting (4 new blogs)',
    taskType: 'aeo-geo', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — AEO/GEO (4 New Blog Pages)', assigneeKey: 'bisma',
    goal: 'Increase snippet and AEO extraction rates.',
    description: 'Reformat the 4 new blogs into snippet-friendly structures.',
    steps: [
      'Identify sections to restructure',
      'Reformat into lists, tables, short paragraphs',
      'Add question-form H2/H3s',
      'Track snippet wins',
    ],
  },
  {
    title: 'Voice search optimization (4 new blogs)',
    taskType: 'aeo-geo', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — AEO/GEO (4 New Blog Pages)', assigneeKey: 'bisma',
    goal: 'Capture conversational queries.',
    description: 'Target natural-language question queries across the 4 blogs.',
    steps: [
      'Identify natural-language target queries',
      'Add question-form headings',
      'Provide concise direct answers',
      'Improve mobile UX/speed',
    ],
  },
  {
    title: 'Entity-based SEO optimization (4 new blogs)',
    taskType: 'aeo-geo', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — AEO/GEO (4 New Blog Pages)', assigneeKey: 'bisma',
    goal: 'Strengthen entity coverage on new content.',
    description: 'Reinforce entity mentions, metadata, and structured data on the 4 blogs.',
    steps: [
      'Identify primary entities per blog',
      'Align naming and metadata',
      'Add structured data (sameAs, about)',
      'Interlink related entities',
    ],
  },

  // GSC Monitoring (4)
  {
    title: 'Coverage report & indexing monitoring',
    taskType: 'reporting', priority: 'HIGH',
    milestone: 'A. Ongoing SEO — GSC Monitoring', assigneeKey: 'sami',
    goal: 'Keep priority pages indexed and healthy.',
    description: 'Monitor Coverage/Indexing reports weekly and fix root causes.',
    steps: [
      'Review Coverage weekly',
      'Triage excluded/errored URLs',
      'Fix robots/canonical/duplicate issues',
      'Request re-indexing',
    ],
  },
  {
    title: 'Crawl error fixes from GSC',
    taskType: 'crawl-fix', priority: 'HIGH',
    milestone: 'A. Ongoing SEO — GSC Monitoring', assigneeKey: 'sami',
    goal: 'Reduce crawl waste and broken paths.',
    description: 'Close out crawl errors reported in GSC.',
    steps: [
      'Export GSC crawl errors',
      'Classify by error type',
      'Deploy fixes',
      'Verify resolution',
    ],
  },
  {
    title: 'Content insights & performance analysis',
    taskType: 'reporting', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — GSC Monitoring', assigneeKey: 'sami',
    goal: 'Turn GSC data into editorial decisions.',
    description: 'Analyse queries, pages, and CTR to guide content priorities.',
    steps: [
      'Pull GSC performance data',
      'Identify rising/falling queries and pages',
      'Flag candidates for optimization',
      'Share insights with content team',
    ],
  },
  {
    title: 'Sitemap submission monitoring',
    taskType: 'reporting', priority: 'MEDIUM',
    milestone: 'A. Ongoing SEO — GSC Monitoring', assigneeKey: 'sami',
    goal: 'Keep sitemaps accurate and discoverable.',
    description: 'Verify sitemap health and discovery in GSC.',
    steps: [
      'Check sitemap status',
      'Remove invalid/noindex URLs',
      'Add new pages promptly',
      'Track indexed counts',
    ],
  },

  // ═══ B. SEO Foundation Setup ═══

  // B. Initial Technical Audit (5)
  {
    title: 'Complete website technical SEO audit',
    taskType: 'technical-seo', priority: 'CRITICAL',
    milestone: 'B. Foundation — Initial Technical Audit', assigneeKey: 'sami',
    goal: 'Establish a clear baseline of technical SEO health.',
    description: 'Run a full technical SEO audit across crawl, index, render, and performance signals.',
    steps: [
      'Run Screaming Frog / Sitebulb crawl',
      'Review GSC + CWV + indexation reports',
      'Document issues with severity',
      'Publish prioritized fix plan',
    ],
  },
  {
    title: 'XML sitemap optimization & segmentation',
    taskType: 'technical-seo', priority: 'HIGH',
    milestone: 'B. Foundation — Initial Technical Audit', assigneeKey: 'sami',
    goal: 'Help search engines discover all priority pages.',
    description: 'Review, segment, and submit clean XML sitemaps.',
    steps: [
      'Audit current sitemap content',
      'Remove invalid / noindex URLs',
      'Split into logical sections',
      'Submit in GSC',
    ],
  },
  {
    title: 'Robots.txt review',
    taskType: 'technical-seo', priority: 'HIGH',
    milestone: 'B. Foundation — Initial Technical Audit', assigneeKey: 'sami',
    goal: 'Ensure robots rules do not block important pages.',
    description: 'Review robots.txt and make sure only intended resources are blocked.',
    steps: [
      'Audit all Disallow rules',
      'Verify priority pages are crawlable',
      'Fix any inadvertent blocks',
      'Re-test with GSC robots tester',
    ],
  },
  {
    title: 'Canonical tags audit',
    taskType: 'technical-seo', priority: 'HIGH',
    milestone: 'B. Foundation — Initial Technical Audit', assigneeKey: 'sami',
    goal: 'Resolve duplicate-indexing issues.',
    description: 'Audit canonical tag coverage and fix conflicts.',
    steps: [
      'Crawl to identify missing / conflicting canonicals',
      'Set self-canonicals where appropriate',
      'Resolve parameter / pagination canonicals',
      'Verify in GSC Coverage',
    ],
  },
  {
    title: '3xx / 4xx error identification and fixes',
    taskType: 'crawl-fix', priority: 'HIGH',
    milestone: 'B. Foundation — Initial Technical Audit', assigneeKey: 'sami',
    goal: 'Stop wasting crawl budget on broken / redirecting URLs.',
    description: 'Identify 3xx/4xx errors and either fix links or restore pages.',
    steps: [
      'Export 3xx / 4xx from crawl',
      'Fix internal links pointing to them',
      'Restore or redirect broken URLs',
      'Re-crawl and verify',
    ],
  },

  // B. SEO Integrations (4)
  {
    title: 'Google Analytics setup',
    taskType: 'reporting', priority: 'CRITICAL',
    milestone: 'B. Foundation — SEO Integrations', assigneeKey: 'hammad',
    goal: 'Ensure reliable traffic and conversion measurement.',
    description: 'Set up or verify GA4 with proper data streams and events.',
    steps: [
      'Create / verify GA4 property',
      'Install tracking code sitewide',
      'Define key events (conversions)',
      'QA via DebugView',
    ],
  },
  {
    title: 'Google Search Console setup',
    taskType: 'reporting', priority: 'CRITICAL',
    milestone: 'B. Foundation — SEO Integrations', assigneeKey: 'hammad',
    goal: 'Enable end-to-end GSC visibility.',
    description: 'Verify property, submit sitemap, and grant access.',
    steps: [
      'Verify domain property',
      'Submit XML sitemap',
      'Set preferred settings',
      'Grant team access',
    ],
  },
  {
    title: 'Google Tag Manager integration',
    taskType: 'reporting', priority: 'HIGH',
    milestone: 'B. Foundation — SEO Integrations', assigneeKey: 'hammad',
    goal: 'Centralize tag deployment.',
    description: 'Install GTM container and migrate existing tags into it.',
    steps: [
      'Install GTM container sitewide',
      'Migrate existing tags into GTM',
      'QA triggers and tag fires',
      'Publish container',
    ],
  },
  {
    title: 'Conversion tracking setup (forms, calls, events)',
    taskType: 'reporting', priority: 'HIGH',
    milestone: 'B. Foundation — SEO Integrations', assigneeKey: 'hammad',
    goal: 'Measure all key conversions reliably.',
    description: 'Track form submissions, calls, and key events end-to-end.',
    steps: [
      'List all conversion events',
      'Implement triggers (GTM)',
      'Connect to GA4 / Ads',
      'QA end-to-end',
    ],
  },

  // B. Core On-Page SEO (6)
  {
    title: 'Meta tags optimization — foundation pass',
    taskType: 'on-page-seo', priority: 'HIGH',
    milestone: 'B. Foundation — Core On-Page SEO', assigneeKey: 'uzma',
    goal: 'Bring every indexable page to a baseline meta standard.',
    description: 'Site-wide meta title + description optimization pass.',
    steps: [
      'Export all indexable URLs',
      'Draft compliant titles + metas',
      'Deploy via CMS',
      'Monitor CTR movement',
    ],
  },
  {
    title: 'Image optimization (alt text, compression)',
    taskType: 'on-page-seo', priority: 'MEDIUM',
    milestone: 'B. Foundation — Core On-Page SEO', assigneeKey: 'uzma',
    goal: 'Speed up pages and improve accessibility / image search.',
    description: 'Compress images and add descriptive alt text site-wide.',
    steps: [
      'Inventory images by size',
      'Compress / convert to WebP',
      'Add descriptive alt text',
      'Re-test page speed',
    ],
  },
  {
    title: 'URL structure fixes',
    taskType: 'on-page-seo', priority: 'HIGH',
    milestone: 'B. Foundation — Core On-Page SEO', assigneeKey: 'mudassar',
    goal: 'Clean URL patterns across the site.',
    description: 'Address URL structure debt (param bloat, long slugs, case issues) with 301s.',
    steps: [
      'Audit URL patterns',
      'Propose new structure',
      'Plan 301s',
      'Deploy and verify',
    ],
  },
  {
    title: 'Internal linking setup',
    taskType: 'link-building', priority: 'MEDIUM',
    milestone: 'B. Foundation — Core On-Page SEO', assigneeKey: 'mudassar',
    goal: 'Establish a strong internal linking foundation.',
    description: 'Add contextual links from high-authority pages to priority pages.',
    steps: [
      'Map priority pages',
      'Identify linking hubs',
      'Add contextual links',
      'Re-crawl and verify',
    ],
  },
  {
    title: 'Add clear above-the-fold CTAs',
    taskType: 'cro', priority: 'MEDIUM',
    milestone: 'B. Foundation — Core On-Page SEO', assigneeKey: 'mudassar',
    goal: 'Ensure every priority page has a clear primary CTA ATF.',
    description: 'Add or improve above-the-fold CTAs on priority pages.',
    steps: [
      'Audit ATF CTA presence',
      'Design clear primary CTAs',
      'Deploy and verify on mobile',
      'Measure CTR',
    ],
  },
  {
    title: 'Navigation menu optimization',
    taskType: 'ux-audit', priority: 'MEDIUM',
    milestone: 'B. Foundation — Core On-Page SEO', assigneeKey: 'developer',
    goal: 'Make the primary navigation intuitive and SEO-friendly.',
    description: 'Rework primary nav structure and labels for clarity and crawlability.',
    steps: [
      'Audit current nav structure',
      'Simplify labels and hierarchy',
      'Deploy and QA on mobile',
      'Validate crawl paths',
    ],
  },

  // B. GBP Foundation (4)
  {
    title: 'Google Business Profile setup',
    taskType: 'local-seo', priority: 'HIGH',
    milestone: 'B. Foundation — GBP Foundation', assigneeKey: 'hamza',
    goal: 'Establish a strong local presence on Google.',
    description: 'Create or claim and fully set up the GBP listing.',
    steps: [
      'Claim / create the GBP listing',
      'Verify ownership',
      'Complete all profile fields',
      'Publish first post',
    ],
  },
  {
    title: 'Business information optimization (NAP)',
    taskType: 'local-seo', priority: 'HIGH',
    milestone: 'B. Foundation — GBP Foundation', assigneeKey: 'hamza',
    goal: 'Ensure consistent NAP across the web.',
    description: 'Align business Name, Address, Phone across site, GBP, and citations.',
    steps: [
      'Define the canonical NAP',
      'Update site footer / contact pages',
      'Update GBP to match',
      'Align across citations',
    ],
  },
  {
    title: 'GBP category & service setup',
    taskType: 'local-seo', priority: 'MEDIUM',
    milestone: 'B. Foundation — GBP Foundation', assigneeKey: 'hamza',
    goal: 'Maximise GBP category and service coverage.',
    description: 'Pick the right primary + secondary categories and list all services.',
    steps: [
      'Research competitor categories',
      'Set primary + secondary categories',
      'Add full services list',
      'Add attributes and products',
    ],
  },
  {
    title: 'GBP initial posts & updates',
    taskType: 'local-seo', priority: 'MEDIUM',
    milestone: 'B. Foundation — GBP Foundation', assigneeKey: 'hamza',
    goal: 'Signal active management to Google.',
    description: 'Publish a starter set of GBP posts, offers, and updates.',
    steps: [
      'Draft 4 opening posts',
      'Add offers / events if relevant',
      'Publish and schedule cadence',
      'Monitor insights',
    ],
  },

  // B. Local Citation / Directory Submission (3)
  {
    title: 'Business listing creation on directories',
    taskType: 'local-seo', priority: 'MEDIUM',
    milestone: 'B. Foundation — Local Citation / Directory Submission', assigneeKey: 'hamza',
    goal: 'Expand discoverable citations.',
    description: 'Create listings on major local and niche directories.',
    steps: [
      'Build directory target list',
      'Submit with canonical NAP',
      'Verify and track live URLs',
      'Watch for duplicates',
    ],
  },
  {
    title: 'NAP consistency check across citations',
    taskType: 'local-seo', priority: 'MEDIUM',
    milestone: 'B. Foundation — Local Citation / Directory Submission', assigneeKey: 'hamza',
    goal: 'Remove conflicting NAP signals.',
    description: 'Audit existing citations and fix NAP inconsistencies.',
    steps: [
      'Pull existing citations',
      'Identify inconsistencies',
      'Update or request corrections',
      'Re-verify',
    ],
  },
  {
    title: 'Directory submissions (local & niche)',
    taskType: 'local-seo', priority: 'MEDIUM',
    milestone: 'B. Foundation — Local Citation / Directory Submission', assigneeKey: 'hamza',
    goal: 'Keep building citation depth.',
    description: 'Continue submitting to quality local and niche directories.',
    steps: [
      'Queue next-tier directories',
      'Submit with canonical NAP',
      'Track live listings',
      'Report citation growth',
    ],
  },

  // B. Reporting (3)
  {
    title: 'Work completed summary report',
    taskType: 'reporting', priority: 'MEDIUM',
    milestone: 'B. Foundation — Reporting', assigneeKey: 'sami',
    goal: 'Give the client a clean view of foundation work done.',
    description: 'Document all foundation tasks completed with before/after evidence.',
    steps: [
      'Collect evidence (screens, exports)',
      'Write concise write-up per section',
      'Design the deck',
      'Share with stakeholders',
    ],
  },
  {
    title: 'Initial insights report (benchmarks, indexing improvements)',
    taskType: 'reporting', priority: 'MEDIUM',
    milestone: 'B. Foundation — Reporting', assigneeKey: 'sami',
    goal: 'Baseline KPIs for the quarter ahead.',
    description: 'Publish baseline metrics and indexing/traffic uplift already observed.',
    steps: [
      'Pull baseline GA/GSC metrics',
      'Compare vs pre-work period',
      'Highlight early wins',
      'Publish the report',
    ],
  },
  {
    title: 'Final output report (work summary + issues fixed)',
    taskType: 'reporting', priority: 'MEDIUM',
    milestone: 'B. Foundation — Reporting', assigneeKey: 'sami',
    goal: 'Close the loop on foundation scope.',
    description: 'Deliver a final report of foundation output: tasks completed, issues fixed, remaining risks.',
    steps: [
      'Consolidate task statuses',
      'List issues fixed with evidence',
      'Call out remaining risks',
      'Share final report',
    ],
  },
];
